<?php

namespace Blogger\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getLatestBlogs($limit = null){
        $qb= $this->createQueryBuilder('b')
                ->addOrderBy('b.created_at','DESC')
                ->getQuery();
        
        if($limit){
            $qb->setMaxResults($limit);
        }
                
        try{
            $blog = $qb->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            $blog = null;
        }
        return $blog;
    }
}
