parameters:
#    blogger_blog.example.class: Blogger\BlogBundle\Example

services:
    blogger_blog.form.enquiry:
        class: Blogger\BlogBundle\Form\EnquiryType
        tags: 
            - { name: form.type, alias: enquiry }
    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
        tags:
            - { name: twig.extension }
