Blogger\BlogBundle\Entity\Enquiry:
    properties:
        name: 
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
        subject:
            - NotBlank: ~
            - Length: 
                max: 50
        body:
            - NotBlank: ~
            - Length: 
                min: 50
Blogger\BlogBundle\Entity\Comment:
    properties:
        username:
            - NotBlank: ~
        comment:
            - NotBlank: ~