Blogger\BlogBundle\Entity\Blog:
    type: entity
    repositoryClass: Blogger\BlogBundle\Repository\BlogRepository
    table: blog
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            
    fields:
        title:
            type: string
        author:
            type: text
            length: 100
        blog:
            type: string
        image:
            type: text
            length: 20
        tags:
            type: text
        created_at:
            type: datetime
        updated_at:
            type: datetime
        slug:
            type: string
            
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: blog
            
            
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setSlugValue]
        preUpdate: [setUpdatedAtValue]
        
