Blogger\BlogBundle\Entity\Comment:
    type: entity
    repositoryClass: Blogger\BlogBundle\Repository\CommentRepository
    table: comment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
        comment:
            type: text
        approved:
            type: boolean
        created_at: 
            type: datetime
        updated_at:
            type: datetime
            nullable: true
    manyToOne:
        blog:
            targetEntity: Blog
            inversedBy: comments
            JoinColumn:
                name: blog_id
                referencedColumn: id
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue]
        preUpdate: [setUpdatedAtValue]
    
